[versions]
kotlin = "2.3.0"
apache-commons-text = "1.15.0"
apache-commons-lang3 = "3.20.0"
jnativehook = "2.1.0"
defaultdepot = "1.9.7"
legiblelogger = "1.6.7"
colorcomposer = "1.0.8"
flatlaf = "3.7"
json = "20220320"
mslinks = "0.0.2+5"
grgit = "4.1.1"
shadow = "8.1.1"

[libraries]
jnativehook = { group = "com.1stleg", name = "jnativehook", version.ref = "jnativehook" }
apache-commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "apache-commons-text" }
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apache-commons-lang3" }
defaultdepot = { group = "org.capturecoop", name = "defaultdepot", version.ref = "defaultdepot" }
legiblelogger = { group = "org.capturecoop", name = "legiblelogger", version.ref = "legiblelogger" }
colorcomposer = { group = "org.capturecoop", name = "colorcomposer", version.ref = "colorcomposer" }
flatlaf = { group = "com.formdev", name = "flatlaf", version.ref = "flatlaf" }
json = { group = "org.json", name = "json", version.ref = "json" }
mslinks = { group = "com.erigir", name = "mslinks", version.ref = "mslinks" }

[bundles]
apache-commons = [ "apache-commons-text", "apache-commons-lang3" ]
capturecoop = [ "defaultdepot", "legiblelogger", "colorcomposer" ]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }