# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SnipSniper development build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Dtype=dev

    - uses: actions/upload-artifact@v2
      name: Uploading jar
      with:
        name: jar
        path: build/libs/SnipSniper.jar

    - name: Get filename with version and build
      run:  |
        echo 'VERSION<<EOF' >> $GITHUB_ENV
        java -jar build/libs/SnipSniper.jar -version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Rename jar
      run: mv build/libs/SnipSniper.jar " "build/libs/${{env.VERSION}}.jar"
    - name: Upload to website
      uses: fjogeleit/http-request-action@master
      with:
        url: https://snipsniper.org/upload.php
        method: "POST"
        data: '{"password": "${{ secrets.WEBSITE_UPLOAD }}"}'
        files: '{ "file": "build/libs/${{env.VERSION}}.jar" }'