# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SnipSniper release build

on:
  release:
    types: [ published ]
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Checkout submodules
    #  uses: textbook/git-checkout-submodule-action@master
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Dtype=stable
    - name: Set up JDK 16 (for jpackage)
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Custom make file
      run: ./make.bat full

    - uses: papeloto/action-zip@v1
      name: Zipping folder
      with:
        files: release/SnipSniper_Portable_Win/
        dest: release/SnipSniper_Portable_Win.zip

    - name: Upload assets to GitHub
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'release/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
